### ISSUE TITLE
Upcoming Unicode failure in eq_or_diff under 5.28

### ISSUE THREAD

**Issue by belg4mit** [Ovid/Test-Differences#14]
http://www.cpantesters.org/cpan/report/e01f5d52-58be-11e7-a257-994259d30835

**Comment by DrHyde** [comment]
I'm gonna guess that you reported this on the wrong project, cos that looks like a bug in Text-FIGlet.

In any case, I've added tests to prove that it handles non-ASCII data correctly, in e894fd507. If you still think this is a bug in Test-Differences please re-open this and clarify exactly what the bug is.
